source "https://rubygems.org"

# Specify your gem's dependencies in url_common.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"
gem "fuzzyurl", '~> 0.9.0'
gem 'mechanize', '~> 2.6'
gem "byebug"
